#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-urwid
Version  : 1.3.1
Release  : 16
URL      : http://pypi.debian.net/urwid/urwid-1.3.1.tar.gz
Source0  : http://pypi.debian.net/urwid/urwid-1.3.1.tar.gz
Summary  : A full-featured console (xterm et al.) user interface library
Group    : Development/Tools
License  : LGPL-2.1
Requires: python-urwid-legacypython
Requires: python-urwid-python3
Requires: python-urwid-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: ignore-decode-errors.patch

%description
Urwid is a console user interface library for Python.

%package legacypython
Summary: legacypython components for the python-urwid package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the python-urwid package.


%package python
Summary: python components for the python-urwid package.
Group: Default
Requires: python-urwid-legacypython
Requires: python-urwid-python3

%description python
python components for the python-urwid package.


%package python3
Summary: python3 components for the python-urwid package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-urwid package.


%prep
%setup -q -n urwid-1.3.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507170538
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.6/site-packages python3 setup.py test || :
%install
export SOURCE_DATE_EPOCH=1507170538
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
